var GAME_LEVELS =[
   ["                                                            ",
	"    x  x  xxxx  x     x      xx   xx                        ",
	"    x  x  x     x     x     x  x  xx                        ",
	"    xxxx  xxx   x     x     x  x  xx                        ",
	"    x  x  x     x     x     x  x                            ",
	"    x  x  xxxx  xxx   xxx    xx   xx                        ",
	"                                                            ",
	"                                      x                     ",
	"    @                                x!x                    ",
	"                                    x!!!x                   ",
	"                                     x!x          o         ",
    "                  o                   v     xxxxxxx         ",
	"                                                  x         ",
	"        xxxxxxxxxxxxxxxxxxxxxxxxxxx               x         ",
	"        x                                         x         ",
	"        x  o                               xxxxx  x         ",
	"        x            xxxxxxx xxx                  x         ",
	"  x     xxxxxxxxxxx  x                   o        x         ",
	"  x                  x                   x        x         ",
	"  x            o     x            x xx!!!x        x         ",
	"  x        xxxxxxxxxxx               xxxxx        x         ",
	"  x                                               x         ",
	"  xxxxxxx!!!!!!!!!!!!                             x         ",
	"       xxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         "],
   ["                                                           !",
	"         x  x   xx  x     x  xxx   x     x   xxxx          !",
	"         x  x  x  x  x   x    x    x x   x   x             !",
	"         xxxx  xxxx   x x     x    x   x x   x xxx         !",
	"         x  x  x!!x    x      x    x    xx   x  x          !",
	"         x  x  x vx    x     xxx   x     x   xxxx          !",
	"                                                           !",
    "                                            xxx            !",
	"                       xxxx  x  x  x    x      x           !",  
	"                       x     x  x  x x  x     x            !",
    "                       xxx   x  x  x  x x    x             !",
    "                       x     x  x  x   xx                  !",
    "        o              x     xxxx  x    x   x              !", 
    "     x=    =x                                              !", 
    "     xxxxxxxx                                              !",
    "            xx                                             !",
    "            xxx                                            !", 
    "              xxx                                          !",
	"                xxx                                        !",
	"                  xxxxx                                    !",
	" @                       xxxx  x =     x                   !",
	"                               xxxxxxxxx                 o !",
	"                               !!!!!!!!!    xxxx         x !",
	" xxx  x =   x     o            !!!                       xx!",
	"      xxxxxxx  xxx xxx                              xx     !",
	"              x!!!x!!!x                            xx      !",
	"              x!!!!!!!x                           xx       !",
	"               x!!!!!x                           xx        !",
	"                x!!!x            o              xx         !",
	"                 x!x            x     xxxx      x          !",
	"                  x    x   x    xxxxx           x          !",
	"                       x!!!x                  o x          !",
	"                       x!!!x                xxxxx          !",
	"                       xxxxx                               !"], 
   ["                                                         v !",
	" v                                                         !",
	"                                                           !",
	"                                                           !",
	"                                                           !",
	"       @                                                   !",
	"       xxxxx  x   x  xxx  xxxx      xxx    xxxx            !",
	"         x    x o x   x   x          x     x               !",
	"         x    xxxxx   x   xxxx       x     xxxx            !",
	"         x    x! !x   x      x       x=       x            !",
	"         x    xv vx  xxx  xxxx     xxxxx   xxxx            !",
    "                                                           !",
	"                                                           !",
	"          xxxxx  x   x   xxxx                       o      !",
    "            x    x   x   x                          xxx    !",
	"            x    xxxxx   xxx    xxxx  x    x  xxx      x   !",
	"            x    x!!!x   x      x     x x  x  x  x    x    !",
	"            x    x v x   xxxx   xxx   x  x x  x   x  x     !",
    "                                x     x   xx  x   x        !",
	"                                xxxx  x    x  xxxx   x     !",
	"                                                           !",
	"                                                         v !",
	"                  o                               xxxx     !",
	"                                                           !",
    "                  xxxxxxx              xxxxx               !",
	"                  x       xx        xxx     xxx        xxx !",
	"               xxxx                              o         !",
	"            xxx       xxxxxx     xxxxx         xxx!!!xxx   !",
	" x =        x        x!!!!!!x o x!!!!!x       xxxx!!!xxxx  !",
	" xxx    xxxxx        x!!!!!!x  x!!!!!!x       xxxxxxxxxxx  !",
    "                      x!!!!!!xx!!!!!!x                     !",
	"                       x!!!!!!x!!!!!x                      !",
	"                        x!!!!!!!!!!x                       !",
	"                         x!!!!!!!!x                        !",
	"                          x!!!!!!x                         !",
	"                           x!!!!x                          !",
    "                            x!!x                           !",
	"                              v                            !",
	"   o                                                       !",
	"   x   x   xx   x   x   xxx  v xxx  xxx                    !",
	"   x!!!x  x  x  x   x   x  x    x   x  x                   !",
	"   xxxxx  x  x  x   x   x   x   x   x   x                  !",
    "     x    x  x  x!!!x   x   x   x   x   x                  !",
	"     x     xx   xxxxx   xxxx   xxx  xxxx                   !",
	"                     =                                     !",
	"            =                                              !",
	"=                  xxx  xxxxx o xx                         !",
	"                    x     x   o xx                         !",
    "                    x     x   o xx                         !",
	"                    x     x                                !",
	"                   xxx    x     xx                         !",
    "                                                           !",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
	
	
	
	
	];
	
	
 
if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
